[package]
name = "repisode"
version = "0.1.0"
edition = "2018"
authors = [ "Taylan Gökkaya<insomnimus.dev@gmail.com>" ]
license = "MIT"

[dependencies]
clap = "3.0.0-beta.2"
glob = "0.3.0"
itertools = "0.10.1"
regex = "1.5.4"
