[package]
name = "repisode"
version = "0.2.1"
edition = "2018"
authors = [ "Taylan Gökkaya<insomnimus.dev@gmail.com>" ]
license = "MIT"

[dependencies]
clap = "3.0.0-beta.2"
once_cell = "1.8.0"
regex = "1.5.4"

[target.'cfg(windows)'.dependencies]
glob = "0.3.0"
itertools = "0.10.1"
